# Generated by Django 4.2.2 on 2023-07-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_post_category_remove_post_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
