# Generated by Django 4.2.3 on 2023-07-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_post_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catagory',
            new_name='category',
        ),
    ]
