# Generated by Django 4.2.3 on 2023-07-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_catagory_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_link',
            field=models.CharField(default='@nulll', max_length=200),
        ),
    ]
